FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-build as build

# Install node dependencies
COPY package*.json ./
RUN npm install --production && npm cache clean --force && rm -rf /tmp/*


FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-run as run

WORKDIR /app
COPY --from=build ./node_modules ./node_modules
COPY index.js package.json ./
COPY lib/ ./lib

# Start the container
CMD ["npm", "start"]
